MUNICIPALITY_AND_PLACE = {
    "Twenterand": [
        "Bruinehaar",
        "De Pollen",
        "Den Ham",
        "Geerdijk",
        "Hallerhoek",
        "Kloosterhaar",
        "Linde",
        "Magele",
        "Meer",
        "Noord-Meer",
        "Sibculo",
        "Vriezenveen",
        "Vroomshoop",
        "Weitemanslanden",
        "Westerhaar-Vriezenveensewijk"
    ],
    "Tubbergen": [
        "Albergen",
        "Fleringen",
        "Geesteren",
        "Haarle",
        "Harbrinkhoek",
        "Hezingen",
        "Klössehoek",
        "Langeveen",
        "Mander",
        "Manderveen",
        "Mariaparochie",
        "Reutum",
        "Tubbergen",
        "Vasse",
        "West Geesteren"
    ], 
    "Dinkelland": [
        "'t Loo",
        "Agelo",
        "Beekdorp",
        "Berghum",
        "Breklenkamp",
        "Denekamp",
        "Deurningen",
        "Dulder",
        "Gammelke",
        "Groot Agelo",
        "Het Stift",
        "Klein Agelo",
        "Lattrop",
        "Lattrop-Breklenkamp",
        "Lemselo",
        "Noord Deurningen",
        "Noordijk",
        "Nutter",
        "Ootmarsum",
        "Oud Ootmarsum",
        "Rossum",
        "Saasveld",
        "Tilligte",
        "Volthe",
        "Weerselo",
        "Zoeke",
    ], 
    "Almelo":[
        "Aadorp",
        "Almelo",
        "Bavinkel",
        "Bornerbroek",
        "Mariaparochie",
        "Tusveld"
    ]

}